/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-09-10 09:15:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Online Mobile Phone Store Management System</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<link rel='stylesheet' href='style.css' />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<h1 class=\"h1-responsive font-weight-bold text-center my-5\">Online\n");
      out.write("\tMobile Phone Store</h1>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("\t<a class=\"navbar-brand\" href=\"#\">Welcome</a>\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t</button>\n");
      out.write("\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\thref=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a></li>\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"ViewMobilePhones\">All\n");
      out.write("\t\t\t\t\tMobile Phones</a></li>\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\thref=\"SimpleLogInForm.html\">Login</a></li>\n");
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\n");
      out.write("\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\n");
      out.write("\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
      out.write("<body>\n");
      out.write("\t<section class=\"text-center my-5\">\n");
      out.write("\t\t<!-- Grid row -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-12 mb-lg-0 mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Featured image -->\n");
      out.write("\t\t\t\t<div class=\"view overlay rounded z-depth-2 mb-4\">\n");
      out.write("\t\t\t\t\t<img class=\"img-fluid\" src=\"Resources/apple-iphone-xs-max-gold.jpg\"\n");
      out.write("\t\t\t\t\t\talt=\"Sample image\"> <a>\n");
      out.write("\t\t\t\t\t\t<div class=\"mask rgba-white-slight\"></div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Category -->\n");
      out.write("\t\t\t\t<a href=\"#!\" class=\"pink-text\">\n");
      out.write("\t\t\t\t\t<h6 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-map pr-2\"></i>Ultimate\n");
      out.write("\t\t\t\t\t</h6>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<!-- Post title -->\n");
      out.write("\t\t\t\t<h4 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t<strong>Apple iPhone Xs Max </strong>\n");
      out.write("\t\t\t\t</h4>\n");
      out.write("\t\t\t\t<!-- Post data -->\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a class=\"font-weight-bold\">$2049</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<!-- Excerpt -->\n");
      out.write("\t\t\t\t<p class=\"dark-grey-text\">iPhone XS Max features a 6.5-inch\n");
      out.write("\t\t\t\t\tSuper Retina display with custom-engineered OLED panels for an HDR\n");
      out.write("\t\t\t\t\tdisplay that provides the industry’s best colour accuracy, as well\n");
      out.write("\t\t\t\t\tas true blacks and remarkable brightness</p>\n");
      out.write("\t\t\t\t<!-- Read more button -->\n");
      out.write("\t\t\t\t<a class=\"btn btn-info btn-rounded btn-md\">Buy now</a>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 mb-md-0 mb-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Featured image -->\n");
      out.write("\t\t\t\t<div class=\"view overlay rounded z-depth-2 mb-4\">\n");
      out.write("\t\t\t\t\t<img class=\"img-fluid\" src=\"Resources/huawei-mate20-rs.jpg\"\n");
      out.write("\t\t\t\t\t\talt=\"Sample image\"> <a>\n");
      out.write("\t\t\t\t\t\t<div class=\"mask rgba-white-slight\"></div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Category -->\n");
      out.write("\t\t\t\t<a href=\"#!\" class=\"deep-orange-text\">\n");
      out.write("\t\t\t\t\t<h6 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-graduation-cap pr-2\"></i>Luxury\n");
      out.write("\t\t\t\t\t</h6>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<!-- Post title -->\n");
      out.write("\t\t\t\t<h4 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t<strong>PORSCHE DESIGN Huawei Mate20 RS</strong>\n");
      out.write("\t\t\t\t</h4>\n");
      out.write("\t\t\t\t<!-- Post data -->\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a class=\"font-weight-bold\">$2599</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<!-- Excerpt -->\n");
      out.write("\t\t\t\t<p class=\"dark-grey-text\">The iconic glass band on the back is\n");
      out.write("\t\t\t\t\tinspired by the Motor Racing seeking the balance of ultimate\n");
      out.write("\t\t\t\t\taesthetics and engineering sophistication. A true masterpiece of\n");
      out.write("\t\t\t\t\tcraftsmanship forged to perfection</p>\n");
      out.write("\t\t\t\t<!-- Read more button -->\n");
      out.write("\t\t\t\t<a class=\"btn btn-info btn-rounded btn-md\">Buy now</a>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 mb-0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Featured image -->\n");
      out.write("\t\t\t\t<div class=\"view overlay rounded z-depth-2 mb-4\">\n");
      out.write("\t\t\t\t\t<img class=\"img-fluid\" src=\"Resources/nokia-4-2.jpg\"\n");
      out.write("\t\t\t\t\t\talt=\"Sample image\"> <a>\n");
      out.write("\t\t\t\t\t\t<div class=\"mask rgba-white-slight\"></div>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Category -->\n");
      out.write("\t\t\t\t<a href=\"#!\" class=\"blue-text\">\n");
      out.write("\t\t\t\t\t<h6 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-fire pr-2\"></i>Classic\n");
      out.write("\t\t\t\t\t</h6>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<!-- Post title -->\n");
      out.write("\t\t\t\t<h4 class=\"font-weight-bold mb-3\">\n");
      out.write("\t\t\t\t\t<strong>Nokia 4.2</strong>\n");
      out.write("\t\t\t\t</h4>\n");
      out.write("\t\t\t\t<!-- Post data -->\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a class=\"font-weight-bold\">$299</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<!-- Excerpt -->\n");
      out.write("\t\t\t\t<p class=\"dark-grey-text\">Free of unnecessary UI changes and\n");
      out.write("\t\t\t\t\thidden processes for longer lasting battery. Better still, your\n");
      out.write("\t\t\t\t\tNokia 4.2 is future-proof with guaranteed software and security\n");
      out.write("\t\t\t\t\tupdates – so it just keeps getting better over time.</p>\n");
      out.write("\t\t\t\t<!-- Read more button -->\n");
      out.write("\t\t\t\t<a class=\"btn btn-info btn-rounded btn-md\">Buy now</a>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Grid column -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Grid row -->\n");
      out.write("\n");
      out.write("\t</Section>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
