/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-09-12 09:14:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import domain.MobilePhone;

public final class ViewMobilePhones_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("domain.MobilePhone");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("/* Float four columns side by side */\n");
      out.write(".column {\n");
      out.write("  float: left;\n");
      out.write("  width: 25%;\n");
      out.write("  padding: 0 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Remove extra left and right margins, due to padding */\n");
      out.write(".row {margin: 0 -5px;}\n");
      out.write("\n");
      out.write("/* Clear floats after the columns */\n");
      out.write(".row:after {\n");
      out.write("  content: \"\";\n");
      out.write("  display: table;\n");
      out.write("  clear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Responsive columns */\n");
      out.write("@media screen and (max-width: 600px) {\n");
      out.write("  .column {\n");
      out.write("    width: 100%;\n");
      out.write("    display: block;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Style the counter cards */\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<title>View Mobile Phones</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<link rel='stylesheet' href='style.css' />\n");
      out.write("</head>\n");
      out.write("<h1 class=\"h1-responsive font-weight-bold text-center my-5\">Online\n");
      out.write("\tMobile Phone Store</h1>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("\t<a class=\"navbar-brand\" href=\"#\">Welcome</a>\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t</button>\n");
      out.write("\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\thref=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a></li>\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"ViewMobilePhones\">All\n");
      out.write("\t\t\t\t\tMobile Phones</a></li>\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\thref=\"SimpleLogInForm.html\">Login</a></li>\n");
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\n");
      out.write("\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\n");
      out.write("\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
      out.write("<body>\n");
      out.write("\t<section class=\"text-center my-5\">\n");
      out.write("\n");
      out.write("\t\t<div class='container'>\n");
      out.write("\t\t\t<table class='table table-bordered table-striped'>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>id</th>\n");
      out.write("\t\t\t\t\t<th>Model Name</th>\n");
      out.write("\t\t\t\t\t<th>Storage Size</th>\n");
      out.write("\t\t\t\t\t<th>Color</th>\n");
      out.write("\t\t\t\t\t<th>Brand</th>\n");
      out.write("\t\t\t\t\t<th>Price</th>\n");
      out.write("\t\t\t\t\t<th>Add to Cart</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t");

						List<MobilePhone> mobiles = (ArrayList<MobilePhone>) request.getAttribute("mobiles");

						for (MobilePhone mobile : mobiles) {
							out.println("<form action=\"cart\" method=\"post\">");
							out.print("<tr><td>" + mobile.getMobilePhoneId() + "</td><td>" + mobile.getModelName() + "</td>"
									+ "<td>" + mobile.getStorageSize() 
									+ "</td><td>" + mobile.getColor() + "</td>"
									+ "<td>"
									+ mobile.getBrand() + "</td><td>" + mobile.getPrice() + "</td>"
									+ "<td colspan=\"2\" align=\"center\"><button type=\"submit\" name=\"isbn\" value=\""
									+ mobile.getId() + "\" class=\"btn btn-default\">Add to Cart</button></td></tr>");
							out.println("</form>");
						}
					
      out.write("\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t");

						List<MobilePhone> mobiless = (ArrayList<MobilePhone>) request.getAttribute("mobiles");

						for (MobilePhone mobile : mobiless) {
							out.println("<div class=\"column\">");
							out.println("<div class=\"card\"\">");
							out.println("<img src=\"Resources/apple-iphone-xs-max-gold.jpg\" class=\"card-img-top\" alt=\"...\">");
							out.println("<div class=\"card-body\">");
							out.println("<h5 class=\"card-title\">"+mobile.getModelName()+"</h5>");
							out.println("<p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the cards content.</p>");
							out.println("<a href=\"#\" class=\"btn btn-primary\">View Detail</a>");
							out.println("</div></div></div>");
						}
					
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
